apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kspan
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kspan
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kspan
subjects:
- kind: ServiceAccount
  name: kspan
  namespace: {{ .Release.Namespace }}
